# Generated by Django 2.2 on 2021-11-04 04:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('login_app', '0002_auto_20210822_1957'),
        ('wall_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='message',
            name='liked_by',
            field=models.ManyToManyField(related_name='messages_liked', to='login_app.User'),
        ),
    ]
